toastyArchive/config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :pictures

end

toastyArchive/app/models/picture.rb
class Picture < ActiveRecord::Base
  def change
    create_table :pictures do |t|
      t.date :date
      t.string :title
      t.string :url

      t.timestamps null :false
    end
  end
end

toastyArchive/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

toastyArchive/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    # render text: "Saving a picture. URL: #{params[:url]}, Title #{params[:title]}, Date #{params[:date]} "
    @picture = Picture.new(picture_params)
      if @picture.save
        redirect_to pictures_url
      else
        render :new
      end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update_attributes(picture_params)
      redirect_to "/pictures/#{@picture.id}"
    else
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_url
  end

    private
    def picture_params
      params.require(:picture).permit(:title, :date, :url)
    end
end

toastyArchive/app/helpers/application_helper.rb
module ApplicationHelper
end

toastyArchive/app/helpers/pictures_helper.rb
module PicturesHelper
end

toastyArchive/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToastyArchive</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

toastyArchive/app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>

<p>
  <%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
<p>
  <%= f.label :title %> <br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :date %> <br>
  <%= f.text_field :date %>
</p>
<p>
  <%= f.label :url %> <br>
  <%= f.text_field :url %>
</p>
<p>
  <%= f.submit %>
</p>

<% end %>

toastyArchive/app/views/pictures/index.html.erb
<h1>Pictures!(Currently <%= @pictures.length %> toasties)</h1>
<%= link_to "New Picture", "/pictures/new" %>

<% @pictures.each do |picture| %>
  <p><%= picture.title %>, <%= picture.date %></p>
  <%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
<%end%>

toastyArchive/app/views/pictures/new.html.erb
<h1>Get more toasty!</h1>
<%= link_to "Back to Pictures", pictures_url %>
<%= form_for @picture do |f| %>
  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :date %> <br>
    <%= f.text_field :date %>
  </p>
  <p>
    <%= f.label :url %> <br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.submit "Save" %>
  </p>

<% end %>

toastyArchive/app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", pictures_url %>
<p><%= @picture.title %>, <%= @picture.date %></p>
<%= link_to "Back to Pictures", pictures_url %> | <%= link_to "Edit", edit_picture_path(@picture) %> | <%= link_to "Delete", @picture, method: :delete, data: {confirm: "Are you sure you want to delete this picture?"} %>
<%= image_tag @picture.url %>